use std::collections::{BTreeSet, HashSet};
use std::path::PathBuf;

use anyhow::Result;
use chrono::Utc;
use owo_colors::OwoColorize;

use crate::audit::cross_reference::cross_reference;
use crate::audit::findings::Finding;
use crate::cli::args::ScaffoldArgs;
use crate::config::Config;
use crate::parser::dotenv;
use crate::scanner::walker;

pub fn run(args: &ScaffoldArgs) -> Result<()> {
    let root = PathBuf::from(&args.root).canonicalize()?;

    // Load config
    let mut config = if let Some(ref cfg_path) = args.config {
        Config::load_from(&PathBuf::from(cfg_path))?
    } else {
        Config::load(&root)?
    };

    // We only need missing/undocumented — disable expensive checks
    config.secrets.enabled = false;
    config.git.enabled = false;

    // Scan source files
    let scan_result = walker::scan_directory(&root, &config)?;

    // Parse existing .env files
    let env_files = dotenv::find_env_files(&root)?;

    // Cross-reference to find missing keys
    let shell_env: std::collections::HashMap<String, String> = std::env::vars().collect();
    let findings = cross_reference(&scan_result.references, &env_files, &shell_env, &config);

    // Collect keys to scaffold (sorted)
    let mut keys: BTreeSet<String> = BTreeSet::new();

    for finding in &findings {
        match finding {
            Finding::Missing { key, .. } => {
                keys.insert(key.clone());
            }
            Finding::Undocumented { key, .. } if args.include_undocumented => {
                keys.insert(key.clone());
            }
            _ => {}
        }
    }

    if keys.is_empty() {
        println!(
            "  {} No missing keys found — nothing to scaffold.",
            "✓".green()
        );
        return Ok(());
    }

    // Resolve output path relative to root
    let output_path = root.join(&args.output);

    // Read existing keys from the target file (if it exists) so we don't duplicate
    let existing_keys: HashSet<String> = if output_path.exists() && !args.force {
        read_keys_from_file(&output_path)?
    } else {
        HashSet::new()
    };

    // Only new keys
    let new_keys: Vec<&str> = keys
        .iter()
        .filter(|k| !existing_keys.contains(*k))
        .map(|k| k.as_str())
        .collect();

    if new_keys.is_empty() {
        println!(
            "  {} All {} missing keys are already present in {}",
            "✓".green(),
            keys.len(),
            args.output
        );
        return Ok(());
    }

    // Build the block to write
    let block = build_block(&new_keys, output_path.exists() && !args.force);

    // Dry-run: just print
    if args.dry_run {
        println!(
            "\n  {} Dry run — would write to {}\n",
            "[preview]".bright_yellow(),
            args.output.bright_cyan()
        );
        println!("{}", block.dimmed());
        println!(
            "  {} {} key(s) would be added. Use without --dry-run to write.",
            "→".bright_yellow(),
            new_keys.len()
        );
        return Ok(());
    }

    // Write / append
    if output_path.exists() && !args.force {
        // Append to existing file
        use std::io::Write;
        let mut file = std::fs::OpenOptions::new()
            .append(true)
            .open(&output_path)?;
        file.write_all(block.as_bytes())?;

        println!(
            "\n  {} Appended {} key(s) to {}\n",
            "✓".green(),
            new_keys.len().to_string().bold(),
            output_path.display().to_string().bright_cyan()
        );
    } else {
        // Create (or overwrite with --force)
        std::fs::write(&output_path, &block)?;

        println!(
            "\n  {} Created {} with {} key(s)\n",
            "✓".green(),
            output_path.display().to_string().bright_cyan(),
            new_keys.len().to_string().bold()
        );
    }

    // Print the keys that were written
    for key in &new_keys {
        println!("    {} {}=", "·".dimmed(), key.bright_white());
    }

    println!();
    println!(
        "  {} Fill in the values, then run {} to verify.",
        "→".bright_yellow(),
        "enspect audit".bright_cyan()
    );
    println!();

    Ok(())
}

/// Build the text block to write / append.
fn build_block(keys: &[&str], is_append: bool) -> String {
    let mut out = String::new();

    if is_append {
        // Section divider when appending to an existing file
        out.push('\n');
        out.push_str(&format!(
            "# ── Added by enspect scaffold ({})\n",
            Utc::now().format("%Y-%m-%d")
        ));
    } else {
        // Fresh file header
        out.push_str(&format!(
            "# Generated by enspect scaffold — {}\n",
            Utc::now().format("%Y-%m-%d")
        ));
        out.push_str("# Fill in the values below.\n");
        out.push('\n');
    }

    for key in keys {
        out.push_str(key);
        out.push('=');
        out.push('\n');
    }

    out
}

/// Parse all KEY= lines from an existing env file to avoid duplicates.
fn read_keys_from_file(path: &PathBuf) -> Result<HashSet<String>> {
    let content = std::fs::read_to_string(path)?;
    let mut keys = HashSet::new();
    for line in content.lines() {
        let line = line.trim();
        // Skip blank lines and comments
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(eq_pos) = line.find('=') {
            let key = line[..eq_pos].trim().to_string();
            if !key.is_empty() {
                keys.insert(key);
            }
        }
    }
    Ok(keys)
}
